package com.psc.pt.model.user;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_info
 */
public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_check_id
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Long userCheckId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.real_name
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.sex
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.photo_path
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String photoPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.phone
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.email
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.hospital_id
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Long hospitalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.hospital_name
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String hospitalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.section_id
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Long sectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.section_name
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String sectionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_introduction
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String userIntroduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @FieldComment null
     *
     * @return the value of user_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @FieldComment null
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_check_id
     *
     * @FieldComment null
     *
     * @return the value of user_info.user_check_id
     *
     * @mbggenerated
     */
    public Long getUserCheckId() {
        return userCheckId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_check_id
     *
     * @FieldComment null
     *
     * @param userCheckId the value for user_info.user_check_id
     *
     * @mbggenerated
     */
    public void setUserCheckId(Long userCheckId) {
        this.userCheckId = userCheckId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.real_name
     *
     * @FieldComment null
     *
     * @return the value of user_info.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.real_name
     *
     * @FieldComment null
     *
     * @param realName the value for user_info.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.sex
     *
     * @FieldComment null
     *
     * @return the value of user_info.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.sex
     *
     * @FieldComment null
     *
     * @param sex the value for user_info.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.photo_path
     *
     * @FieldComment null
     *
     * @return the value of user_info.photo_path
     *
     * @mbggenerated
     */
    public String getPhotoPath() {
        return photoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.photo_path
     *
     * @FieldComment null
     *
     * @param photoPath the value for user_info.photo_path
     *
     * @mbggenerated
     */
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath == null ? null : photoPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.phone
     *
     * @FieldComment null
     *
     * @return the value of user_info.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.phone
     *
     * @FieldComment null
     *
     * @param phone the value for user_info.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.email
     *
     * @FieldComment null
     *
     * @return the value of user_info.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.email
     *
     * @FieldComment null
     *
     * @param email the value for user_info.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.hospital_id
     *
     * @FieldComment null
     *
     * @return the value of user_info.hospital_id
     *
     * @mbggenerated
     */
    public Long getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.hospital_id
     *
     * @FieldComment null
     *
     * @param hospitalId the value for user_info.hospital_id
     *
     * @mbggenerated
     */
    public void setHospitalId(Long hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.hospital_name
     *
     * @FieldComment null
     *
     * @return the value of user_info.hospital_name
     *
     * @mbggenerated
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.hospital_name
     *
     * @FieldComment null
     *
     * @param hospitalName the value for user_info.hospital_name
     *
     * @mbggenerated
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.section_id
     *
     * @FieldComment null
     *
     * @return the value of user_info.section_id
     *
     * @mbggenerated
     */
    public Long getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.section_id
     *
     * @FieldComment null
     *
     * @param sectionId the value for user_info.section_id
     *
     * @mbggenerated
     */
    public void setSectionId(Long sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.section_name
     *
     * @FieldComment null
     *
     * @return the value of user_info.section_name
     *
     * @mbggenerated
     */
    public String getSectionName() {
        return sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.section_name
     *
     * @FieldComment null
     *
     * @param sectionName the value for user_info.section_name
     *
     * @mbggenerated
     */
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName == null ? null : sectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_introduction
     *
     * @FieldComment null
     *
     * @return the value of user_info.user_introduction
     *
     * @mbggenerated
     */
    public String getUserIntroduction() {
        return userIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_introduction
     *
     * @FieldComment null
     *
     * @param userIntroduction the value for user_info.user_introduction
     *
     * @mbggenerated
     */
    public void setUserIntroduction(String userIntroduction) {
        this.userIntroduction = userIntroduction == null ? null : userIntroduction.trim();
    }
}