package com.psc.pt.model.user;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_group
 */
public class UserGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.id
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.group_name
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.features
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String features;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.main_src
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String mainSrc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.id
     *
     * @FieldComment null
     *
     * @return the value of user_group.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.id
     *
     * @FieldComment null
     *
     * @param id the value for user_group.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.group_name
     *
     * @FieldComment null
     *
     * @return the value of user_group.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.group_name
     *
     * @FieldComment null
     *
     * @param groupName the value for user_group.group_name
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.features
     *
     * @FieldComment null
     *
     * @return the value of user_group.features
     *
     * @mbggenerated
     */
    public String getFeatures() {
        return features;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.features
     *
     * @FieldComment null
     *
     * @param features the value for user_group.features
     *
     * @mbggenerated
     */
    public void setFeatures(String features) {
        this.features = features == null ? null : features.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.main_src
     *
     * @FieldComment null
     *
     * @return the value of user_group.main_src
     *
     * @mbggenerated
     */
    public String getMainSrc() {
        return mainSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.main_src
     *
     * @FieldComment null
     *
     * @param mainSrc the value for user_group.main_src
     *
     * @mbggenerated
     */
    public void setMainSrc(String mainSrc) {
        this.mainSrc = mainSrc == null ? null : mainSrc.trim();
    }
}