package com.psc.pt.model.user;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_check
 */
public class UserCheck {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_check.id
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_check.user_name
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_check.password
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_check.salt
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_check.group_id
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_check.is_delete
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_check.id
     *
     * @FieldComment null
     *
     * @return the value of user_check.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_check.id
     *
     * @FieldComment null
     *
     * @param id the value for user_check.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_check.user_name
     *
     * @FieldComment null
     *
     * @return the value of user_check.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_check.user_name
     *
     * @FieldComment null
     *
     * @param userName the value for user_check.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_check.password
     *
     * @FieldComment null
     *
     * @return the value of user_check.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_check.password
     *
     * @FieldComment null
     *
     * @param password the value for user_check.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_check.salt
     *
     * @FieldComment null
     *
     * @return the value of user_check.salt
     *
     * @mbggenerated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_check.salt
     *
     * @FieldComment null
     *
     * @param salt the value for user_check.salt
     *
     * @mbggenerated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_check.group_id
     *
     * @FieldComment null
     *
     * @return the value of user_check.group_id
     *
     * @mbggenerated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_check.group_id
     *
     * @FieldComment null
     *
     * @param groupId the value for user_check.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_check.is_delete
     *
     * @FieldComment null
     *
     * @return the value of user_check.is_delete
     *
     * @mbggenerated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_check.is_delete
     *
     * @FieldComment null
     *
     * @param isDelete the value for user_check.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }
}