package com.psc.pt.dao.user;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.psc.pt.model.user.UserGroup;

public class UserGroupSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     * @param record  Model for table user_group
     * @return   The combine SQL for table user_group
     *
     * @mbggenerated
     */
    public String insertSelective(UserGroup record) {
        BEGIN();
        INSERT_INTO("user_group");
        
        if (record.getGroupName() != null) {
            VALUES("group_name", "#{groupName,jdbcType=VARCHAR}");
        }
        
        if (record.getFeatures() != null) {
            VALUES("features", "#{features,jdbcType=VARCHAR}");
        }
        
        if (record.getMainSrc() != null) {
            VALUES("main_src", "#{mainSrc,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     * @param record  Model for table user_group
     * @return   The combine SQL for table user_group
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(UserGroup record) {
        BEGIN();
        UPDATE("user_group");
        
        if (record.getGroupName() != null) {
            SET("group_name = #{groupName,jdbcType=VARCHAR}");
        }
        
        if (record.getFeatures() != null) {
            SET("features = #{features,jdbcType=VARCHAR}");
        }
        
        if (record.getMainSrc() != null) {
            SET("main_src = #{mainSrc,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=BIGINT}");
        
        return SQL();
    }
}