package com.psc.pt.dao.user;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.psc.pt.model.user.UserInfo;

public class UserInfoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     * @param record  Model for table user_info
     * @return   The combine SQL for table user_info
     *
     * @mbggenerated
     */
    public String insertSelective(UserInfo record) {
        BEGIN();
        INSERT_INTO("user_info");
        
        if (record.getUserCheckId() != null) {
            VALUES("user_check_id", "#{userCheckId,jdbcType=BIGINT}");
        }
        
        if (record.getRealName() != null) {
            VALUES("real_name", "#{realName,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            VALUES("sex", "#{sex,jdbcType=VARCHAR}");
        }
        
        if (record.getPhotoPath() != null) {
            VALUES("photo_path", "#{photoPath,jdbcType=VARCHAR}");
        }
        
        if (record.getPhone() != null) {
            VALUES("phone", "#{phone,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            VALUES("email", "#{email,jdbcType=VARCHAR}");
        }
        
        if (record.getHospitalId() != null) {
            VALUES("hospital_id", "#{hospitalId,jdbcType=BIGINT}");
        }
        
        if (record.getHospitalName() != null) {
            VALUES("hospital_name", "#{hospitalName,jdbcType=VARCHAR}");
        }
        
        if (record.getSectionId() != null) {
            VALUES("section_id", "#{sectionId,jdbcType=BIGINT}");
        }
        
        if (record.getSectionName() != null) {
            VALUES("section_name", "#{sectionName,jdbcType=VARCHAR}");
        }
        
        if (record.getUserIntroduction() != null) {
            VALUES("user_introduction", "#{userIntroduction,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     * @param record  Model for table user_info
     * @return   The combine SQL for table user_info
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(UserInfo record) {
        BEGIN();
        UPDATE("user_info");
        
        if (record.getUserCheckId() != null) {
            SET("user_check_id = #{userCheckId,jdbcType=BIGINT}");
        }
        
        if (record.getRealName() != null) {
            SET("real_name = #{realName,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            SET("sex = #{sex,jdbcType=VARCHAR}");
        }
        
        if (record.getPhotoPath() != null) {
            SET("photo_path = #{photoPath,jdbcType=VARCHAR}");
        }
        
        if (record.getPhone() != null) {
            SET("phone = #{phone,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            SET("email = #{email,jdbcType=VARCHAR}");
        }
        
        if (record.getHospitalId() != null) {
            SET("hospital_id = #{hospitalId,jdbcType=BIGINT}");
        }
        
        if (record.getHospitalName() != null) {
            SET("hospital_name = #{hospitalName,jdbcType=VARCHAR}");
        }
        
        if (record.getSectionId() != null) {
            SET("section_id = #{sectionId,jdbcType=BIGINT}");
        }
        
        if (record.getSectionName() != null) {
            SET("section_name = #{sectionName,jdbcType=VARCHAR}");
        }
        
        if (record.getUserIntroduction() != null) {
            SET("user_introduction = #{userIntroduction,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=BIGINT}");
        
        return SQL();
    }
}