package com.psc.pt.dao.pacs;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.psc.pt.model.pacs.CasePacs;

public class CasePacsSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_pacs
     * @param record  Model for table case_pacs
     * @return   The combine SQL for table case_pacs
     *
     * @mbggenerated
     */
    public String insertSelective(CasePacs record) {
        BEGIN();
        INSERT_INTO("case_pacs");
        
        if (record.getCaseId() != null) {
            VALUES("case_id", "#{caseId,jdbcType=BIGINT}");
        }
        
        if (record.getAccno() != null) {
            VALUES("accno", "#{accno,jdbcType=VARCHAR}");
        }
        
        if (record.getModalityId() != null) {
            VALUES("modality_id", "#{modalityId,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgcode() != null) {
            VALUES("OrgCode", "#{orgcode,jdbcType=VARCHAR}");
        }
        
        if (record.getModality() != null) {
            VALUES("modality", "#{modality,jdbcType=VARCHAR}");
        }
        
        if (record.getItem() != null) {
            VALUES("item", "#{item,jdbcType=VARCHAR}");
        }
        
        if (record.getCheckdate() != null) {
            VALUES("checkdate", "#{checkdate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getReadUrl() != null) {
            VALUES("read_url", "#{readUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getImgUrl() != null) {
            VALUES("img_url", "#{imgUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDelete() != null) {
            VALUES("is_delete", "#{isDelete,jdbcType=CHAR}");
        }
        
        if (record.getTemp1() != null) {
            VALUES("temp1", "#{temp1,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp2() != null) {
            VALUES("temp2", "#{temp2,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp3() != null) {
            VALUES("temp3", "#{temp3,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp4() != null) {
            VALUES("temp4", "#{temp4,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_pacs
     * @param record  Model for table case_pacs
     * @return   The combine SQL for table case_pacs
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(CasePacs record) {
        BEGIN();
        UPDATE("case_pacs");
        
        if (record.getCaseId() != null) {
            SET("case_id = #{caseId,jdbcType=BIGINT}");
        }
        
        if (record.getAccno() != null) {
            SET("accno = #{accno,jdbcType=VARCHAR}");
        }
        
        if (record.getModalityId() != null) {
            SET("modality_id = #{modalityId,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgcode() != null) {
            SET("OrgCode = #{orgcode,jdbcType=VARCHAR}");
        }
        
        if (record.getModality() != null) {
            SET("modality = #{modality,jdbcType=VARCHAR}");
        }
        
        if (record.getItem() != null) {
            SET("item = #{item,jdbcType=VARCHAR}");
        }
        
        if (record.getCheckdate() != null) {
            SET("checkdate = #{checkdate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getReadUrl() != null) {
            SET("read_url = #{readUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getImgUrl() != null) {
            SET("img_url = #{imgUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDelete() != null) {
            SET("is_delete = #{isDelete,jdbcType=CHAR}");
        }
        
        if (record.getTemp1() != null) {
            SET("temp1 = #{temp1,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp2() != null) {
            SET("temp2 = #{temp2,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp3() != null) {
            SET("temp3 = #{temp3,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp4() != null) {
            SET("temp4 = #{temp4,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=BIGINT}");
        
        return SQL();
    }
}