package com.psc.pt.dao.pacs;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.psc.pt.model.pacs.CaseDig;

public class CaseDigSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_dig
     * @param record  Model for table case_dig
     * @return   The combine SQL for table case_dig
     *
     * @mbggenerated
     */
    public String insertSelective(CaseDig record) {
        BEGIN();
        INSERT_INTO("case_dig");
        
        if (record.getCaseId() != null) {
            VALUES("case_id", "#{caseId,jdbcType=BIGINT}");
        }
        
        if (record.getDigSee() != null) {
            VALUES("dig_see", "#{digSee,jdbcType=VARCHAR}");
        }
        
        if (record.getDigMain() != null) {
            VALUES("dig_main", "#{digMain,jdbcType=VARCHAR}");
        }
        
        if (record.getDigDoctorId() != null) {
            VALUES("dig_doctor_id", "#{digDoctorId,jdbcType=BIGINT}");
        }
        
        if (record.getDigDoctorName() != null) {
            VALUES("dig_doctor_name", "#{digDoctorName,jdbcType=VARCHAR}");
        }
        
        if (record.getDigDate() != null) {
            VALUES("dig_date", "#{digDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getTemp1() != null) {
            VALUES("temp1", "#{temp1,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp2() != null) {
            VALUES("temp2", "#{temp2,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp3() != null) {
            VALUES("temp3", "#{temp3,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp4() != null) {
            VALUES("temp4", "#{temp4,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_dig
     * @param record  Model for table case_dig
     * @return   The combine SQL for table case_dig
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(CaseDig record) {
        BEGIN();
        UPDATE("case_dig");
        
        if (record.getCaseId() != null) {
            SET("case_id = #{caseId,jdbcType=BIGINT}");
        }
        
        if (record.getDigSee() != null) {
            SET("dig_see = #{digSee,jdbcType=VARCHAR}");
        }
        
        if (record.getDigMain() != null) {
            SET("dig_main = #{digMain,jdbcType=VARCHAR}");
        }
        
        if (record.getDigDoctorId() != null) {
            SET("dig_doctor_id = #{digDoctorId,jdbcType=BIGINT}");
        }
        
        if (record.getDigDoctorName() != null) {
            SET("dig_doctor_name = #{digDoctorName,jdbcType=VARCHAR}");
        }
        
        if (record.getDigDate() != null) {
            SET("dig_date = #{digDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getTemp1() != null) {
            SET("temp1 = #{temp1,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp2() != null) {
            SET("temp2 = #{temp2,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp3() != null) {
            SET("temp3 = #{temp3,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp4() != null) {
            SET("temp4 = #{temp4,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=BIGINT}");
        
        return SQL();
    }
}