package com.psc.pt.dao.pacs;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.psc.pt.model.pacs.DigPacs;

public class DigPacsSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dig_pacs
     * @param record  Model for table dig_pacs
     * @return   The combine SQL for table dig_pacs
     *
     * @mbggenerated
     */
    public String insertSelective(DigPacs record) {
        BEGIN();
        INSERT_INTO("dig_pacs");
        
        if (record.getIsDelete() != null) {
            VALUES("is_delete", "#{isDelete,jdbcType=CHAR}");
        }
        
        if (record.getType() != null) {
            VALUES("type", "#{type,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getpId() != null) {
            VALUES("p_id", "#{pId,jdbcType=BIGINT}");
        }
        
        if (record.getTemp1() != null) {
            VALUES("temp1", "#{temp1,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp2() != null) {
            VALUES("temp2", "#{temp2,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp3() != null) {
            VALUES("temp3", "#{temp3,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp4() != null) {
            VALUES("temp4", "#{temp4,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp5() != null) {
            VALUES("temp5", "#{temp5,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp6() != null) {
            VALUES("temp6", "#{temp6,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dig_pacs
     * @param record  Model for table dig_pacs
     * @return   The combine SQL for table dig_pacs
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(DigPacs record) {
        BEGIN();
        UPDATE("dig_pacs");
        
        if (record.getIsDelete() != null) {
            SET("is_delete = #{isDelete,jdbcType=CHAR}");
        }
        
        if (record.getType() != null) {
            SET("type = #{type,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getpId() != null) {
            SET("p_id = #{pId,jdbcType=BIGINT}");
        }
        
        if (record.getTemp1() != null) {
            SET("temp1 = #{temp1,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp2() != null) {
            SET("temp2 = #{temp2,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp3() != null) {
            SET("temp3 = #{temp3,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp4() != null) {
            SET("temp4 = #{temp4,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp5() != null) {
            SET("temp5 = #{temp5,jdbcType=VARCHAR}");
        }
        
        if (record.getTemp6() != null) {
            SET("temp6 = #{temp6,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=BIGINT}");
        
        return SQL();
    }
}