package com.psc.pt.model.pacs;

import java.io.Serializable;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table case_list_info
 */
public class CaseListInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.id
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.status
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.patient_name
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.patient_sex
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String patientSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.patient_age
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Integer patientAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.visit_type
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String visitType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.patient_phone
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String patientPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.patient_no
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String patientNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.check_no
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String checkNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.case_no
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String caseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.item
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String item;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.modality
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String modality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.doctor_id
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Long doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.send_doctor_id
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Long sendDoctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.send_doctor_name
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String sendDoctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.send_hospital_id
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Long sendHospitalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.send_hospital_name
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String sendHospitalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.send_date
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Date sendDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.get_date
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Date getDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.dig_date
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Date digDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.back_date
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Date backDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.missing_time
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Long missingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.inId
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Long inid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.is_delete
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.is_appoint
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String isAppoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.temp1
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String temp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.temp2
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String temp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.temp3
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String temp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.temp4
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String temp4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_list_info.temp5
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String temp5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.id
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.id
     *
     * @FieldComment null
     *
     * @param id the value for case_list_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.status
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.status
     *
     * @FieldComment null
     *
     * @param status the value for case_list_info.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.patient_name
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.patient_name
     *
     * @mbggenerated
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.patient_name
     *
     * @FieldComment null
     *
     * @param patientName the value for case_list_info.patient_name
     *
     * @mbggenerated
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.patient_sex
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.patient_sex
     *
     * @mbggenerated
     */
    public String getPatientSex() {
        return patientSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.patient_sex
     *
     * @FieldComment null
     *
     * @param patientSex the value for case_list_info.patient_sex
     *
     * @mbggenerated
     */
    public void setPatientSex(String patientSex) {
        this.patientSex = patientSex == null ? null : patientSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.patient_age
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.patient_age
     *
     * @mbggenerated
     */
    public Integer getPatientAge() {
        return patientAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.patient_age
     *
     * @FieldComment null
     *
     * @param patientAge the value for case_list_info.patient_age
     *
     * @mbggenerated
     */
    public void setPatientAge(Integer patientAge) {
        this.patientAge = patientAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.visit_type
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.visit_type
     *
     * @mbggenerated
     */
    public String getVisitType() {
        return visitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.visit_type
     *
     * @FieldComment null
     *
     * @param visitType the value for case_list_info.visit_type
     *
     * @mbggenerated
     */
    public void setVisitType(String visitType) {
        this.visitType = visitType == null ? null : visitType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.patient_phone
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.patient_phone
     *
     * @mbggenerated
     */
    public String getPatientPhone() {
        return patientPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.patient_phone
     *
     * @FieldComment null
     *
     * @param patientPhone the value for case_list_info.patient_phone
     *
     * @mbggenerated
     */
    public void setPatientPhone(String patientPhone) {
        this.patientPhone = patientPhone == null ? null : patientPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.patient_no
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.patient_no
     *
     * @mbggenerated
     */
    public String getPatientNo() {
        return patientNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.patient_no
     *
     * @FieldComment null
     *
     * @param patientNo the value for case_list_info.patient_no
     *
     * @mbggenerated
     */
    public void setPatientNo(String patientNo) {
        this.patientNo = patientNo == null ? null : patientNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.check_no
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.check_no
     *
     * @mbggenerated
     */
    public String getCheckNo() {
        return checkNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.check_no
     *
     * @FieldComment null
     *
     * @param checkNo the value for case_list_info.check_no
     *
     * @mbggenerated
     */
    public void setCheckNo(String checkNo) {
        this.checkNo = checkNo == null ? null : checkNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.case_no
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.case_no
     *
     * @mbggenerated
     */
    public String getCaseNo() {
        return caseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.case_no
     *
     * @FieldComment null
     *
     * @param caseNo the value for case_list_info.case_no
     *
     * @mbggenerated
     */
    public void setCaseNo(String caseNo) {
        this.caseNo = caseNo == null ? null : caseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.item
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.item
     *
     * @mbggenerated
     */
    public String getItem() {
        return item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.item
     *
     * @FieldComment null
     *
     * @param item the value for case_list_info.item
     *
     * @mbggenerated
     */
    public void setItem(String item) {
        this.item = item == null ? null : item.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.modality
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.modality
     *
     * @mbggenerated
     */
    public String getModality() {
        return modality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.modality
     *
     * @FieldComment null
     *
     * @param modality the value for case_list_info.modality
     *
     * @mbggenerated
     */
    public void setModality(String modality) {
        this.modality = modality == null ? null : modality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.doctor_id
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.doctor_id
     *
     * @mbggenerated
     */
    public Long getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.doctor_id
     *
     * @FieldComment null
     *
     * @param doctorId the value for case_list_info.doctor_id
     *
     * @mbggenerated
     */
    public void setDoctorId(Long doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.send_doctor_id
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.send_doctor_id
     *
     * @mbggenerated
     */
    public Long getSendDoctorId() {
        return sendDoctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.send_doctor_id
     *
     * @FieldComment null
     *
     * @param sendDoctorId the value for case_list_info.send_doctor_id
     *
     * @mbggenerated
     */
    public void setSendDoctorId(Long sendDoctorId) {
        this.sendDoctorId = sendDoctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.send_doctor_name
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.send_doctor_name
     *
     * @mbggenerated
     */
    public String getSendDoctorName() {
        return sendDoctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.send_doctor_name
     *
     * @FieldComment null
     *
     * @param sendDoctorName the value for case_list_info.send_doctor_name
     *
     * @mbggenerated
     */
    public void setSendDoctorName(String sendDoctorName) {
        this.sendDoctorName = sendDoctorName == null ? null : sendDoctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.send_hospital_id
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.send_hospital_id
     *
     * @mbggenerated
     */
    public Long getSendHospitalId() {
        return sendHospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.send_hospital_id
     *
     * @FieldComment null
     *
     * @param sendHospitalId the value for case_list_info.send_hospital_id
     *
     * @mbggenerated
     */
    public void setSendHospitalId(Long sendHospitalId) {
        this.sendHospitalId = sendHospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.send_hospital_name
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.send_hospital_name
     *
     * @mbggenerated
     */
    public String getSendHospitalName() {
        return sendHospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.send_hospital_name
     *
     * @FieldComment null
     *
     * @param sendHospitalName the value for case_list_info.send_hospital_name
     *
     * @mbggenerated
     */
    public void setSendHospitalName(String sendHospitalName) {
        this.sendHospitalName = sendHospitalName == null ? null : sendHospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.send_date
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.send_date
     *
     * @mbggenerated
     */
    public Date getSendDate() {
        return sendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.send_date
     *
     * @FieldComment null
     *
     * @param sendDate the value for case_list_info.send_date
     *
     * @mbggenerated
     */
    public void setSendDate(Date sendDate) {
        this.sendDate = sendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.get_date
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.get_date
     *
     * @mbggenerated
     */
    public Date getGetDate() {
        return getDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.get_date
     *
     * @FieldComment null
     *
     * @param getDate the value for case_list_info.get_date
     *
     * @mbggenerated
     */
    public void setGetDate(Date getDate) {
        this.getDate = getDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.dig_date
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.dig_date
     *
     * @mbggenerated
     */
    public Date getDigDate() {
        return digDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.dig_date
     *
     * @FieldComment null
     *
     * @param digDate the value for case_list_info.dig_date
     *
     * @mbggenerated
     */
    public void setDigDate(Date digDate) {
        this.digDate = digDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.back_date
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.back_date
     *
     * @mbggenerated
     */
    public Date getBackDate() {
        return backDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.back_date
     *
     * @FieldComment null
     *
     * @param backDate the value for case_list_info.back_date
     *
     * @mbggenerated
     */
    public void setBackDate(Date backDate) {
        this.backDate = backDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.missing_time
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.missing_time
     *
     * @mbggenerated
     */
    public Long getMissingTime() {
        return missingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.missing_time
     *
     * @FieldComment null
     *
     * @param missingTime the value for case_list_info.missing_time
     *
     * @mbggenerated
     */
    public void setMissingTime(Long missingTime) {
        this.missingTime = missingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.inId
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.inId
     *
     * @mbggenerated
     */
    public Long getInid() {
        return inid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.inId
     *
     * @FieldComment null
     *
     * @param inid the value for case_list_info.inId
     *
     * @mbggenerated
     */
    public void setInid(Long inid) {
        this.inid = inid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.is_delete
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.is_delete
     *
     * @mbggenerated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.is_delete
     *
     * @FieldComment null
     *
     * @param isDelete the value for case_list_info.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.is_appoint
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.is_appoint
     *
     * @mbggenerated
     */
    public String getIsAppoint() {
        return isAppoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.is_appoint
     *
     * @FieldComment null
     *
     * @param isAppoint the value for case_list_info.is_appoint
     *
     * @mbggenerated
     */
    public void setIsAppoint(String isAppoint) {
        this.isAppoint = isAppoint == null ? null : isAppoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.temp1
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.temp1
     *
     * @mbggenerated
     */
    public String getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.temp1
     *
     * @FieldComment null
     *
     * @param temp1 the value for case_list_info.temp1
     *
     * @mbggenerated
     */
    public void setTemp1(String temp1) {
        this.temp1 = temp1 == null ? null : temp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.temp2
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.temp2
     *
     * @mbggenerated
     */
    public String getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.temp2
     *
     * @FieldComment null
     *
     * @param temp2 the value for case_list_info.temp2
     *
     * @mbggenerated
     */
    public void setTemp2(String temp2) {
        this.temp2 = temp2 == null ? null : temp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.temp3
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.temp3
     *
     * @mbggenerated
     */
    public String getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.temp3
     *
     * @FieldComment null
     *
     * @param temp3 the value for case_list_info.temp3
     *
     * @mbggenerated
     */
    public void setTemp3(String temp3) {
        this.temp3 = temp3 == null ? null : temp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.temp4
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.temp4
     *
     * @mbggenerated
     */
    public String getTemp4() {
        return temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.temp4
     *
     * @FieldComment null
     *
     * @param temp4 the value for case_list_info.temp4
     *
     * @mbggenerated
     */
    public void setTemp4(String temp4) {
        this.temp4 = temp4 == null ? null : temp4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_list_info.temp5
     *
     * @FieldComment null
     *
     * @return the value of case_list_info.temp5
     *
     * @mbggenerated
     */
    public String getTemp5() {
        return temp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_list_info.temp5
     *
     * @FieldComment null
     *
     * @param temp5 the value for case_list_info.temp5
     *
     * @mbggenerated
     */
    public void setTemp5(String temp5) {
        this.temp5 = temp5 == null ? null : temp5.trim();
    }
}