package com.psc.pt.model.pacs;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table case_dig
 */
public class CaseDig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_dig.id
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_dig.case_id
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Long caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_dig.dig_see
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String digSee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_dig.dig_main
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String digMain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_dig.dig_doctor_id
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Long digDoctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_dig.dig_doctor_name
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String digDoctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_dig.dig_date
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Date digDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_dig.temp1
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String temp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_dig.temp2
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String temp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_dig.temp3
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String temp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_dig.temp4
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String temp4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_dig.id
     *
     * @FieldComment null
     *
     * @return the value of case_dig.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_dig.id
     *
     * @FieldComment null
     *
     * @param id the value for case_dig.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_dig.case_id
     *
     * @FieldComment null
     *
     * @return the value of case_dig.case_id
     *
     * @mbggenerated
     */
    public Long getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_dig.case_id
     *
     * @FieldComment null
     *
     * @param caseId the value for case_dig.case_id
     *
     * @mbggenerated
     */
    public void setCaseId(Long caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_dig.dig_see
     *
     * @FieldComment null
     *
     * @return the value of case_dig.dig_see
     *
     * @mbggenerated
     */
    public String getDigSee() {
        return digSee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_dig.dig_see
     *
     * @FieldComment null
     *
     * @param digSee the value for case_dig.dig_see
     *
     * @mbggenerated
     */
    public void setDigSee(String digSee) {
        this.digSee = digSee == null ? null : digSee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_dig.dig_main
     *
     * @FieldComment null
     *
     * @return the value of case_dig.dig_main
     *
     * @mbggenerated
     */
    public String getDigMain() {
        return digMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_dig.dig_main
     *
     * @FieldComment null
     *
     * @param digMain the value for case_dig.dig_main
     *
     * @mbggenerated
     */
    public void setDigMain(String digMain) {
        this.digMain = digMain == null ? null : digMain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_dig.dig_doctor_id
     *
     * @FieldComment null
     *
     * @return the value of case_dig.dig_doctor_id
     *
     * @mbggenerated
     */
    public Long getDigDoctorId() {
        return digDoctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_dig.dig_doctor_id
     *
     * @FieldComment null
     *
     * @param digDoctorId the value for case_dig.dig_doctor_id
     *
     * @mbggenerated
     */
    public void setDigDoctorId(Long digDoctorId) {
        this.digDoctorId = digDoctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_dig.dig_doctor_name
     *
     * @FieldComment null
     *
     * @return the value of case_dig.dig_doctor_name
     *
     * @mbggenerated
     */
    public String getDigDoctorName() {
        return digDoctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_dig.dig_doctor_name
     *
     * @FieldComment null
     *
     * @param digDoctorName the value for case_dig.dig_doctor_name
     *
     * @mbggenerated
     */
    public void setDigDoctorName(String digDoctorName) {
        this.digDoctorName = digDoctorName == null ? null : digDoctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_dig.dig_date
     *
     * @FieldComment null
     *
     * @return the value of case_dig.dig_date
     *
     * @mbggenerated
     */
    public Date getDigDate() {
        return digDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_dig.dig_date
     *
     * @FieldComment null
     *
     * @param digDate the value for case_dig.dig_date
     *
     * @mbggenerated
     */
    public void setDigDate(Date digDate) {
        this.digDate = digDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_dig.temp1
     *
     * @FieldComment null
     *
     * @return the value of case_dig.temp1
     *
     * @mbggenerated
     */
    public String getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_dig.temp1
     *
     * @FieldComment null
     *
     * @param temp1 the value for case_dig.temp1
     *
     * @mbggenerated
     */
    public void setTemp1(String temp1) {
        this.temp1 = temp1 == null ? null : temp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_dig.temp2
     *
     * @FieldComment null
     *
     * @return the value of case_dig.temp2
     *
     * @mbggenerated
     */
    public String getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_dig.temp2
     *
     * @FieldComment null
     *
     * @param temp2 the value for case_dig.temp2
     *
     * @mbggenerated
     */
    public void setTemp2(String temp2) {
        this.temp2 = temp2 == null ? null : temp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_dig.temp3
     *
     * @FieldComment null
     *
     * @return the value of case_dig.temp3
     *
     * @mbggenerated
     */
    public String getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_dig.temp3
     *
     * @FieldComment null
     *
     * @param temp3 the value for case_dig.temp3
     *
     * @mbggenerated
     */
    public void setTemp3(String temp3) {
        this.temp3 = temp3 == null ? null : temp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_dig.temp4
     *
     * @FieldComment null
     *
     * @return the value of case_dig.temp4
     *
     * @mbggenerated
     */
    public String getTemp4() {
        return temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_dig.temp4
     *
     * @FieldComment null
     *
     * @param temp4 the value for case_dig.temp4
     *
     * @mbggenerated
     */
    public void setTemp4(String temp4) {
        this.temp4 = temp4 == null ? null : temp4.trim();
    }
}