package com.psc.pt.model.pacs;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table case_pacs
 */
public class CasePacs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_pacs.id
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_pacs.case_id
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Long caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_pacs.accno
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String accno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_pacs.modality_id
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String modalityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_pacs.OrgCode
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String orgcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_pacs.modality
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String modality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_pacs.item
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String item;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_pacs.checkdate
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Date checkdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_pacs.read_url
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String readUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_pacs.img_url
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_pacs.is_delete
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_pacs.temp1
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String temp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_pacs.temp2
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String temp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_pacs.temp3
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String temp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_pacs.temp4
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String temp4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_pacs.id
     *
     * @FieldComment null
     *
     * @return the value of case_pacs.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_pacs.id
     *
     * @FieldComment null
     *
     * @param id the value for case_pacs.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_pacs.case_id
     *
     * @FieldComment null
     *
     * @return the value of case_pacs.case_id
     *
     * @mbggenerated
     */
    public Long getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_pacs.case_id
     *
     * @FieldComment null
     *
     * @param caseId the value for case_pacs.case_id
     *
     * @mbggenerated
     */
    public void setCaseId(Long caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_pacs.accno
     *
     * @FieldComment null
     *
     * @return the value of case_pacs.accno
     *
     * @mbggenerated
     */
    public String getAccno() {
        return accno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_pacs.accno
     *
     * @FieldComment null
     *
     * @param accno the value for case_pacs.accno
     *
     * @mbggenerated
     */
    public void setAccno(String accno) {
        this.accno = accno == null ? null : accno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_pacs.modality_id
     *
     * @FieldComment null
     *
     * @return the value of case_pacs.modality_id
     *
     * @mbggenerated
     */
    public String getModalityId() {
        return modalityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_pacs.modality_id
     *
     * @FieldComment null
     *
     * @param modalityId the value for case_pacs.modality_id
     *
     * @mbggenerated
     */
    public void setModalityId(String modalityId) {
        this.modalityId = modalityId == null ? null : modalityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_pacs.OrgCode
     *
     * @FieldComment null
     *
     * @return the value of case_pacs.OrgCode
     *
     * @mbggenerated
     */
    public String getOrgcode() {
        return orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_pacs.OrgCode
     *
     * @FieldComment null
     *
     * @param orgcode the value for case_pacs.OrgCode
     *
     * @mbggenerated
     */
    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode == null ? null : orgcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_pacs.modality
     *
     * @FieldComment null
     *
     * @return the value of case_pacs.modality
     *
     * @mbggenerated
     */
    public String getModality() {
        return modality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_pacs.modality
     *
     * @FieldComment null
     *
     * @param modality the value for case_pacs.modality
     *
     * @mbggenerated
     */
    public void setModality(String modality) {
        this.modality = modality == null ? null : modality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_pacs.item
     *
     * @FieldComment null
     *
     * @return the value of case_pacs.item
     *
     * @mbggenerated
     */
    public String getItem() {
        return item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_pacs.item
     *
     * @FieldComment null
     *
     * @param item the value for case_pacs.item
     *
     * @mbggenerated
     */
    public void setItem(String item) {
        this.item = item == null ? null : item.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_pacs.checkdate
     *
     * @FieldComment null
     *
     * @return the value of case_pacs.checkdate
     *
     * @mbggenerated
     */
    public Date getCheckdate() {
        return checkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_pacs.checkdate
     *
     * @FieldComment null
     *
     * @param checkdate the value for case_pacs.checkdate
     *
     * @mbggenerated
     */
    public void setCheckdate(Date checkdate) {
        this.checkdate = checkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_pacs.read_url
     *
     * @FieldComment null
     *
     * @return the value of case_pacs.read_url
     *
     * @mbggenerated
     */
    public String getReadUrl() {
        return readUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_pacs.read_url
     *
     * @FieldComment null
     *
     * @param readUrl the value for case_pacs.read_url
     *
     * @mbggenerated
     */
    public void setReadUrl(String readUrl) {
        this.readUrl = readUrl == null ? null : readUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_pacs.img_url
     *
     * @FieldComment null
     *
     * @return the value of case_pacs.img_url
     *
     * @mbggenerated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_pacs.img_url
     *
     * @FieldComment null
     *
     * @param imgUrl the value for case_pacs.img_url
     *
     * @mbggenerated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_pacs.is_delete
     *
     * @FieldComment null
     *
     * @return the value of case_pacs.is_delete
     *
     * @mbggenerated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_pacs.is_delete
     *
     * @FieldComment null
     *
     * @param isDelete the value for case_pacs.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_pacs.temp1
     *
     * @FieldComment null
     *
     * @return the value of case_pacs.temp1
     *
     * @mbggenerated
     */
    public String getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_pacs.temp1
     *
     * @FieldComment null
     *
     * @param temp1 the value for case_pacs.temp1
     *
     * @mbggenerated
     */
    public void setTemp1(String temp1) {
        this.temp1 = temp1 == null ? null : temp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_pacs.temp2
     *
     * @FieldComment null
     *
     * @return the value of case_pacs.temp2
     *
     * @mbggenerated
     */
    public String getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_pacs.temp2
     *
     * @FieldComment null
     *
     * @param temp2 the value for case_pacs.temp2
     *
     * @mbggenerated
     */
    public void setTemp2(String temp2) {
        this.temp2 = temp2 == null ? null : temp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_pacs.temp3
     *
     * @FieldComment null
     *
     * @return the value of case_pacs.temp3
     *
     * @mbggenerated
     */
    public String getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_pacs.temp3
     *
     * @FieldComment null
     *
     * @param temp3 the value for case_pacs.temp3
     *
     * @mbggenerated
     */
    public void setTemp3(String temp3) {
        this.temp3 = temp3 == null ? null : temp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_pacs.temp4
     *
     * @FieldComment null
     *
     * @return the value of case_pacs.temp4
     *
     * @mbggenerated
     */
    public String getTemp4() {
        return temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_pacs.temp4
     *
     * @FieldComment null
     *
     * @param temp4 the value for case_pacs.temp4
     *
     * @mbggenerated
     */
    public void setTemp4(String temp4) {
        this.temp4 = temp4 == null ? null : temp4.trim();
    }
}