package com.psc.pt.model.pacs;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dig_pacs
 */
public class DigPacs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dig_pacs.id
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dig_pacs.is_delete
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dig_pacs.type
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dig_pacs.name
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dig_pacs.p_id
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private Long pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dig_pacs.temp1
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String temp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dig_pacs.temp2
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String temp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dig_pacs.temp3
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String temp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dig_pacs.temp4
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String temp4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dig_pacs.temp5
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String temp5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dig_pacs.temp6
     *
     * @FieldComment null
     *
     * @mbggenerated
     */
    private String temp6;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dig_pacs.id
     *
     * @FieldComment null
     *
     * @return the value of dig_pacs.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dig_pacs.id
     *
     * @FieldComment null
     *
     * @param id the value for dig_pacs.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dig_pacs.is_delete
     *
     * @FieldComment null
     *
     * @return the value of dig_pacs.is_delete
     *
     * @mbggenerated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dig_pacs.is_delete
     *
     * @FieldComment null
     *
     * @param isDelete the value for dig_pacs.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dig_pacs.type
     *
     * @FieldComment null
     *
     * @return the value of dig_pacs.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dig_pacs.type
     *
     * @FieldComment null
     *
     * @param type the value for dig_pacs.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dig_pacs.name
     *
     * @FieldComment null
     *
     * @return the value of dig_pacs.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dig_pacs.name
     *
     * @FieldComment null
     *
     * @param name the value for dig_pacs.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dig_pacs.p_id
     *
     * @FieldComment null
     *
     * @return the value of dig_pacs.p_id
     *
     * @mbggenerated
     */
    public Long getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dig_pacs.p_id
     *
     * @FieldComment null
     *
     * @param pId the value for dig_pacs.p_id
     *
     * @mbggenerated
     */
    public void setpId(Long pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dig_pacs.temp1
     *
     * @FieldComment null
     *
     * @return the value of dig_pacs.temp1
     *
     * @mbggenerated
     */
    public String getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dig_pacs.temp1
     *
     * @FieldComment null
     *
     * @param temp1 the value for dig_pacs.temp1
     *
     * @mbggenerated
     */
    public void setTemp1(String temp1) {
        this.temp1 = temp1 == null ? null : temp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dig_pacs.temp2
     *
     * @FieldComment null
     *
     * @return the value of dig_pacs.temp2
     *
     * @mbggenerated
     */
    public String getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dig_pacs.temp2
     *
     * @FieldComment null
     *
     * @param temp2 the value for dig_pacs.temp2
     *
     * @mbggenerated
     */
    public void setTemp2(String temp2) {
        this.temp2 = temp2 == null ? null : temp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dig_pacs.temp3
     *
     * @FieldComment null
     *
     * @return the value of dig_pacs.temp3
     *
     * @mbggenerated
     */
    public String getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dig_pacs.temp3
     *
     * @FieldComment null
     *
     * @param temp3 the value for dig_pacs.temp3
     *
     * @mbggenerated
     */
    public void setTemp3(String temp3) {
        this.temp3 = temp3 == null ? null : temp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dig_pacs.temp4
     *
     * @FieldComment null
     *
     * @return the value of dig_pacs.temp4
     *
     * @mbggenerated
     */
    public String getTemp4() {
        return temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dig_pacs.temp4
     *
     * @FieldComment null
     *
     * @param temp4 the value for dig_pacs.temp4
     *
     * @mbggenerated
     */
    public void setTemp4(String temp4) {
        this.temp4 = temp4 == null ? null : temp4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dig_pacs.temp5
     *
     * @FieldComment null
     *
     * @return the value of dig_pacs.temp5
     *
     * @mbggenerated
     */
    public String getTemp5() {
        return temp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dig_pacs.temp5
     *
     * @FieldComment null
     *
     * @param temp5 the value for dig_pacs.temp5
     *
     * @mbggenerated
     */
    public void setTemp5(String temp5) {
        this.temp5 = temp5 == null ? null : temp5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dig_pacs.temp6
     *
     * @FieldComment null
     *
     * @return the value of dig_pacs.temp6
     *
     * @mbggenerated
     */
    public String getTemp6() {
        return temp6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dig_pacs.temp6
     *
     * @FieldComment null
     *
     * @param temp6 the value for dig_pacs.temp6
     *
     * @mbggenerated
     */
    public void setTemp6(String temp6) {
        this.temp6 = temp6 == null ? null : temp6.trim();
    }
}